sudo: true
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
before_install:
  - sudo apt update
  - cd src && npm i
  - npm i -g --add-python-to-path --vs2015 --production windows-build-tools
script:
  - npm test
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
